app/routes/dashboard.py
from os import getenv
from flask import Blueprint, render_template
from flask import render_template, session
from flask_login import current_user, login_required
from ..models import Personal_Stat, User
from ..extensions import login_manager


# Create instance
dashboard_bp = Blueprint('dashboard', __name__)

# User loader to get user object from the session when a request is made
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# Main
@dashboard_bp.route("/map", methods = ["GET", "POST"])
@login_required
def map():
    stat = Personal_Stat.query.filter_by(user_id=current_user.user_id).first()
    return render_template("dashboard/map.html", socketio_url = getenv("SOCKETIO_URL"), map_key = getenv("MAP_API_KEY"), personal_stat=stat, username = current_user.username) 

app/routes/home.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required
from app.models import Personal_Stat
from flask_login import current_user

from ..extensions import db
from ..models import User

home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def intro():
    return render_template('home/intro.html')

@home_bp.route('/homepage')
def homepage():
    return render_template('home/homepage.html')

@home_bp.route('/about')
def about():
    return render_template('home/about_us.html')

@home_bp.route('/set-goal', methods = ["GET", "POST"])
def set_goal():
    if request.method == "POST":
        new_goal = request.form.get("goal")
        User.update_goal(user_id = current_user.user_id, new_goal = float(new_goal))
        return render_template("home/homepage.html")
    return render_template("home/set_goal.html")

@home_bp.route('/profile', methods = ["GET", "POST"])
@login_required
def profile():
    stat = Personal_Stat.query.filter_by(user_id=current_user.user_id).first()

    if request.method == "POST":
        weight = request.form.get("weight", type=float)
        height = request.form.get("height", type=float)
        age = request.form.get("age", type=int)

        if stat:
            stat.weight = weight
            stat.height = height
            stat.age = age
        else:
            stat = Personal_Stat(user_id=current_user.user_id, weight=weight, height=height, age=age)
            db.session.add(stat)

        db.session.commit()
        return redirect(url_for("home.profile"))

    return render_template("home/profile.html", username=current_user.username, personal_stat=stat)

@home_bp.route('/statistics')
def statistics():
    return render_template('home/statistics.html')

app/routes/statistics.py
from os import getenv
from flask import Blueprint, render_template
from flask import render_template
from flask_login import current_user, login_required

import datetime

from ..models import User, Run_History
from ..extensions import login_manager

# Month mapping
month_mapping = {
    1: "Jan", 2: "Feb",
    3: "Mar", 4: "Apr",
    5: "May", 6: "Jun",
    7: "Jul", 8: "Aug",
    9: "Sep", 10: "Oct",
    11: "Nov", 12: "Dec"
}

# Create instance
statistics_bp = Blueprint('statistics', __name__)

def get_months(current_month: int, current_year: int) -> list["tuple"]:
    """
    Current month in int. January is 1, February is 2,..., December is 12.
    - Return a list of tuple (str month, year) like.
    """
    six_months_from_now = []
    for i in range(5, -1, -1):
        month = current_month - i
        year = current_year
        if month <= 0:
            month = 12 + month
            year -= 1
        six_months_from_now.append((month, year))
    return six_months_from_now

# User loader to get user object from the session when a request is made
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# Main
@statistics_bp.route("/graph", methods = ["GET", "POST"])
@login_required
def graph():
    user_id = current_user.user_id

    today = datetime.datetime.now()
    current_month = today.month
    current_year = today.year
    
    # Get list of data to put into graph
    six_months_from_now = get_months(current_month = current_month, current_year = current_year)
    six_month_distances = []
    six_month_nums = []
    six_month_calories = []
    for i in range(6):
        month_overall = Run_History.get_overall_month(user_id = user_id, month = six_months_from_now[i][0], year = six_months_from_now[i][1])
        six_month_distances.append(month_overall["total_distance"])
        six_month_nums.append(month_overall["total_run_num"])
        six_month_calories.append(month_overall["total_calories"])

    # Get overall data to put into achievement
    month_overall = Run_History.get_overall_month(user_id = user_id, month = current_month, year = current_year)
    month_distance = round(month_overall["total_distance"], 1)
    month_longest_run = round(month_overall["longest_run"], 1)
    month_pace = round(month_overall["fastest_pace"], 1)

    overall = Run_History.get_overall(user_id = user_id)
    
    total_distance = round(overall["total_distance"], 1)
    longest_run = round(overall["longest_run"], 1)
    fastest_pace = round(overall["fastest_pace"], 1)
    total_run_num = overall["total_run_num"]
    success_rate = overall["success_rate"]

    print(f"\n\n\n\n{six_month_distances}\n\n\n")
    return render_template('home/statistics.html', segment='index',
                           total_distance = total_distance, month_distance = month_distance,
                           longest_run = longest_run, month_longest_run = month_longest_run,
                           fastest_pace = fastest_pace, month_pace = month_pace,
                           total_run_num = total_run_num, success_rate = success_rate,
                           six_months_from_now = six_months_from_now, six_month_distances = six_month_distances,
                           six_month_nums = six_month_nums, six_month_calories = six_month_calories)

app/templates/home/bad_news.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bad_news.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') }}" />
    <link
    href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@400;700&display=swap"
    rel="stylesheet"
  /> 
    <link 
    href="https://fonts.googleapis.com/css2?family=Joan&family=Jomhuria&family=Judson:ital,wght@0,400;0,700;1,400&display=swap" 
    rel="stylesheet">
  >
  </head>
  <body>
    <nav class="navbar">
      <div class="logo">
        <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo"/>
      </div>
      <ul class="nav-links">
        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
        <li><a href="{{ url_for('home.set_goal') }}">About Us</a></li> <!--cần link lại đến trang About Us-->
      </ul>
    
    </nav>


    <div class="background">
      <div class="navbar_background"></div>
      <div class="main">
          <div class="map_placeholder"> </div>

          <div class="time-container">
            <p class="time-label">Time:</p>
            <p class="time-value">00:30:00</p>
          </div>

          <div class="pause-button">
            <img src="{{ url_for('static', filename='images/pause.png') }}" alt="pause" />
        </div>
  
          <div class="end-button">
            <img src="{{ url_for('static', filename='images/end.png') }}" alt="end" />
          </div>

          <div class="distance-container">
            <p class="distance-label">Distance:</p>
            <p class="distance-value">8.5 KM</p>
          </div>

        <div class="congrats_container">
          <p class="congrats_text1">It seems like you are cooked ...</p>
          <p class="continue_text">Tap to continue</p>
        </div>

        <a href="{{ url_for('admin.dashboard') }}" class="click-layer"></a>

      </div>

    </div>

  </body>
</html>

app/templates/home/congrats.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/congrats.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') }}" />
    <link
    href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@400;700&display=swap"
    rel="stylesheet"
  /> 
    <link 
    href="https://fonts.googleapis.com/css2?family=Joan&family=Jomhuria&family=Judson:ital,wght@0,400;0,700;1,400&display=swap" 
    rel="stylesheet">
  >
  </head>
  <body>
    <nav class="navbar">
      <div class="logo">
        <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo"/>
      </div>
      <ul class="nav-links">
        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
        <li><a href="{{ url_for('home.set_goal') }}">About Us</a></li> <!--cần link lại đến trang About Us-->
      </ul>
    
    </nav>


    <div class="background">
      <div class="navbar_background"></div>
      <div class="main">
          <div class="map_placeholder"> </div>

          <div class="time-container">
            <p class="time-label">Time:</p>
            <p class="time-value">00:30:00</p>
          </div>

          <div class="pause-button">
            <img src="{{ url_for('static', filename='images/pause.png') }}" alt="pause" />
        </div>
  
          <div class="end-button">
            <img src="{{ url_for('static', filename='images/end.png') }}" alt="end" />
          </div>

          <div class="distance-container">
            <p class="distance-label">Distance:</p>
            <p class="distance-value">8.5 KM</p>
          </div>

        <div class="congrats_container">
          <p class="congrats_text1">Congrats!</p>
          <p class="congrats_text2">You have escaped from Gulag.</p>
          <p class="continue_text">Tap to continue</p>
        </div>

        <a href="{{ url_for('admin.dashboard') }}" class="click-layer"></a>

      </div>

    </div>

  </body>
</html>

app/templates/home/homepage.html
{% extends "home/layout.html" %} {% block title %} Home {% endblock %} {% block
head %} {{ super() }}
<!-- Link to the CSS Home page -->
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/homepage.css') }}"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@400;700&display=swap"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Joan&display=swap"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,700&display=swap"
  rel="stylesheet"
/>

{% endblock %} {% block content %}

<!-- Main content of the about us page -->
<div class="main_background">
  <img
    src="{{ url_for('static', filename='images/home_background.jpg') }}"
    alt="Homepage Background"
    class="homepage-image"
  />

  <div class="main">
    <!-- The content -->
    <div class="content-container">
      <!-- Heading text -->
      <div class="headline-text">
        <h1>Your freedom<br />starts with<br />a step.</h1>
      </div>

      <!-- Start running butoon -->
      <div class="start-button">
        <a href="{{ url_for('dashboard.map') }}" class="red-button"
          >Start Running</a
        >
      </div>

      <!-- The bottom link -->
      <div class="bottom-links">
        <a href="{{ url_for('home.set_goal') }}" class="setgoal-container"
          >Set your goal</a
        >
        <a href="{{ url_for('statistics.graph') }}" class="statistic-container"
          >My escape logs</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/intro.html
{% extends "home/layout.html" %} {% block title %}Home{% endblock %} {% block
head %} {{ super() }}
<!-- Link to homepage-specific CSS -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/intro.css') }}"/>
<link href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@400;700&display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Joan&display=swap" rel="stylesheet"/>

{% endblock %} {% block content %}
<!-- Header section with background image and fog effect -->
<div class="wrapper">
  <div class="page-header section-dark" style="background-image: url('{{ url_for('static', filename='images/intro_background.png') }}')">
    <div class="filter"></div>
    <div class="content-center">
      <div class="container">
        <div class="title-brand">
        <h1 class="presentation-title">WELCOME TO GULAG RUNNING</h1>
        </div>
          <a href="{{ url_for('auth.login') }}" class="enter-button">The Chase Begin</a>
        </div>
    </div>
    <div
      class="moving-clouds"
      style="background-image: url('https://demos.creative-tim.com/paper-kit-2/assets/img/clouds.png');"></div>
    </div>
</div>
{% endblock %}

app/templates/home/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="UTF-8" />
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/transition.css') }}" />
    {% endblock %}
  </head>

  <body>
    <!-- Background wrapper and main content -->
    <div class="background">
      <!-- Hammer Transition Overlay -->
      <div class="transition-overlay" id="transition-overlay">
        <img
          src="{{ url_for('static', filename='images/hammer.png') }}"
          alt="Hammer"
          class="hammer"
        />

        <!-- Loading text Gulag-->
        <div class="loading-text" id="loading-text">
          <span>G</span><span>u</span><span>l</span><span>a</span><span>g</span>
          <span>&nbsp;</span>
          <span>l</span><span>o</span><span>a</span><span>d</span><span>i</span
          ><span>n</span><span>g</span><span>.</span><span>.</span
          ><span>.</span>
        </div>
      </div>
      <!-- Navbar and main content wrapper -->
      <div class="navbar_background">
        <!-- Navbar -->
        <nav class="navbar">
          <div class="logo">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo" />
          </div>
          <div class="gradient-text">| RUN FOR YOUR LIFE</div>
          <ul class="nav-links">
            <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
            <li><a href="{{ url_for('home.about') }}">About Us</a></li>
            <li><a href="{{ url_for('home.profile') }}">Profile</a></li>
            <li><a role="button" onclick="openModal()">Log out</a></li>
          </ul>

          <!-- Modal -->
          <div id="logoutModal" class="modal">
            <div class="modal-content">
              <div class="modal-icon">
                <img
                  src="{{ url_for('static', filename='images/logout.png') }}"
                  alt="Logout Icon"
                />
              </div>
              <h2>Oh no! You're leaving...</h2>
              <h2>Are you sure?</h2>
              <div class="modal-buttons">
                <button class="btn_modal btn-cancel" onclick="closeModal()">
                  Nah, Just Kidding
                </button>
                <button class="btn_modal btn-danger" onclick="confirmLogout()">
                  Yes, Log Me Out
                </button>
              </div>
            </div>
          </div>

          <!-- Logout Success Modal -->
          <div id="logoutSuccessModal" class="modal">
            <div class="modal-content">
              <div class="modal-icon">
                <img
                  src="{{ url_for('static', filename='images/like.png') }}"
                  alt="Logout Icon"
                />
              </div>
              <h2>You’ve successfully<br />Logged out.</h2>
              <div class="modal-buttons">
                <button class="btn_modal btn-danger" onclick="goToLogin()">
                  Back to Login
                </button>
              </div>
            </div>
          </div>
        </nav>
      </div>
      <div class="main_background">
        {% block content %}
        <!-- Main content goes here -->
        {% endblock %}
      </div>
    </div>
    {% block scripts %}
    <!-- place for JS scripts -->
    <!-- Hammer for page transition-->
    <script src="{{ url_for('static', filename='javascript/transition.js') }}"></script>
    <script src="{{ url_for('static', filename='javascript/logout.js') }}"></script>
    {% endblock %}
  </body>
</html>

app/templates/home/layout_statistics.html
<!--
=========================================================
* Argon Dashboard - v1.2.0
=========================================================
* Product Page: https://www.creative-tim.com/product/argon-dashboard


* Copyright  Creative Tim (http://www.creative-tim.com)
* Coded by www.creative-tim.com



=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="canonical" href="https://appseed.us/admin-dashboards/flask-boilerplate-dashboard-argon">
  
  <title>
    {% block title %}{% endblock %}
  </title>

  <!-- Favicon - loaded as static -->
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/img/brand/favicon.png') }}" type="image/png"/>
  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/vendor/nucleo/css/nucleo.css') }}" type="text/css"/>
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/vendor/@fortawesome/fontawesome-free/css/all.min.css') }}" type="text/css"/>
  <!-- Page plugins -->
  <!-- Argon CSS -->

  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/argon.css') }}" type="text/css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/transition.css') }}" />
</head>

<body>
  <!-- Background wrapper and main content -->
  <div class="background">
    <!-- Hammer Transition Overlay -->
    <div class="transition-overlay" id="transition-overlay">
      <img
        src="{{ url_for('static', filename='images/hammer.png') }}"
        alt="Hammer"
        class="hammer"
      />

      <!-- Loading text Gulag-->
      <div class="loading-text" id="loading-text">
        <span>G</span><span>u</span><span>l</span><span>a</span><span>g</span>
        <span>&nbsp;</span>
        <span>l</span><span>o</span><span>a</span><span>d</span><span>i</span
        ><span>n</span><span>g</span><span>.</span><span>.</span
        ><span>.</span>
      </div>
    </div>
    <!-- Navbar and main content wrapper -->
    <div class="navbar_background">
      <!-- Navbar -->
      <nav class="navbar">
        <div class="logo">
          <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo" />
        </div>
        <div class="gradient-text">| RUN FOR YOUR LIFE</div>
        <ul class="nav-links">
          <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
          <li><a href="{{ url_for('home.about') }}">About Us</a></li>
          <li><a href="{{ url_for('home.profile') }}">Profile</a></li>
          <li><a role="button" onclick="openModal()">Log out</a></li>
        </ul>

<!-- Modal -->
<div id="logoutModal" class="modal">
  <div class="modal-content" style="width: 40%;">
    <div class="modal-icon">
      <img
        src="{{ url_for('static', filename='images/logout.png') }}"
        alt="Logout Icon"
      />
    </div>
    <h2>Oh no! You're leaving...</h2>
    <h2>Are you sure?</h2>
    <div class="modal-buttons">
      <button class="btn_modal btn-cancel" onclick="closeModal()">
        Nah, Just Kidding
      </button>
      <button class="btn_modal btn-danger" onclick="confirmLogout()">
        Yes, Log Me Out
      </button>
    </div>
  </div>
</div>

<!-- Logout Success Modal -->
<div id="logoutSuccessModal" class="modal">
  <div class="modal-content" style="width: 40%;">
    <div class="modal-icon">
      <img
        src="{{ url_for('static', filename='images/like.png') }}"
        alt="Logout Icon"
      />
    </div>
    <h2>You’ve successfully<br />Logged out.</h2>
    <div class="modal-buttons">
      <button class="btn_modal btn-danger" onclick="goToLogin()">
        Back to Login
      </button>
    </div>
  </div>
</div>
      </nav>
    </div>
    <div class="main_background">
        <!-- Main content goes here -->
        {% block content %}
        {% endblock %}
    </div>
  </div>

  {% include "includes/scripts.html" %}

  <!-- Specific JS goes HERE --> 
  <script src="{{ url_for('static', filename='javascript/transition.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/js/argon.js') }}"></script>
  <script src="{{ url_for('static', filename='javascript/logout.js') }}"></script>
  {% block javascripts %}{% endblock javascripts %}
  

</body>

</html>

app/templates/home/profile.html
{% extends "home/layout.html" %} {% block title %} Home {% endblock %} {% block
head %} {{ super() }}

<!-- Link to CSS profile and external font's link -->
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/profile.css') }}"
/>

<link
  href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@400;700&display=swap"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Joan&display=swap"
  rel="stylesheet"
/>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Joan&family=Jomhuria&family=Judson:ital,wght@0,400;0,700;1,400&display=swap"
  rel="stylesheet"
/>
{% endblock%} {% block content%}

<!-- Main content for the profile page -->

<div class="main">
  <!-- The personal information -->
  <div class="profile-container">
    <h1 class="profile_heading">Welcome back, {{ username }}!</h1>
    <form method="POST" class="profile_stats">
      <div class="stat1">
        <span class="age-label">Age</span>
        <input
          class="age-value"
          type="number"
          name="age"
          value="{{ personal_stat.age or '' }}"
          required
        />
      </div>

      <div class="stat2">
        <span class="height-label">Height</span>
        <div class="height-input-wrapper">
          <input
            class="height-value"
            type="number"
            step="0.01"
            name="height"
            value="{{ personal_stat.height or '' }}"
            required
          />
          <span class="height-unit">cm</span>
        </div>
      </div>

      <div class="stat3">
        <span class="weight-label">Weight</span>
        <div class="weight-input-wrapper">
          <input
            class="weight-value"
            type="number"
            step="0.1"
            name="weight"
            value="{{ personal_stat.weight or '' }}"
            required
          />
          <span class="weight-unit">kg</span>
        </div>
      </div>

      <button type="submit" class="btn">Save Changes</button>
    </form>
  </div>
</div>
{% endblock %}

app/templates/home/resume.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/resume.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') }}" />
    <link
    href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@400;700&display=swap"
    rel="stylesheet"
  /> 
    <link 
    href="https://fonts.googleapis.com/css2?family=Joan&family=Jomhuria&family=Judson:ital,wght@0,400;0,700;1,400&display=swap" 
    rel="stylesheet">
  >
  </head>
  <body>
    <nav class="navbar">
      <div class="logo">
        <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo"/>
      </div>
      <ul class="nav-links">
        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
        <li><a href="{{ url_for('home.set_goal') }}">About Us</a></li> <!--cần link lại đến trang About Us-->
      </ul>
    
    </nav>


    <div class="background">
      <div class="navbar_background"></div>
      <div class="main">
        <div class="map_placeholder"> </div>

        <div class="time-container">
          <p class="time-label">Time:</p>
          <p class="time-value">00:30:00</p>
        </div>

        <a href="{{ url_for('home.running') }}" class="resume-button">
        <img src="{{ url_for('static', filename='images/resume.png') }}" alt="resume" />
        </a>

        <div class="end-button">
            <img src="{{ url_for('static', filename='images/end.png') }}" alt="end" />
          </div>

        <div class="distance-container">
          <p class="distance-label">Distance:</p>
          <p class="distance-value">8.5 KM</p>
        </div>

    </div>

  </body>
</html>

app/templates/home/running.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/running.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') }}" />
    <link
    href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@400;700&display=swap"
    rel="stylesheet"
  /> 
    <link 
    href="https://fonts.googleapis.com/css2?family=Joan&family=Jomhuria&family=Judson:ital,wght@0,400;0,700;1,400&display=swap" 
    rel="stylesheet">
  >
  </head>
  <body>
    <nav class="navbar">
      <div class="logo">
        <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo"/>
      </div>
      <ul class="nav-links">
        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
        <li><a href="{{ url_for('home.set_goal') }}">About Us</a></li> <!--cần link lại đến trang About Us-->
      </ul>
      
    </nav>


    <div class="background">
      <div class="navbar_background"></div>
      <div class="main">
        <div class="map_placeholder"> </div>

        <div class="time-container">
          <p class="time-label">Time:</p>
          <p class="time-value">00:30:00</p>
        </div>
        
        <a href="{{ url_for('home.resume') }}" class="pause-button">
          <img src="{{ url_for('static', filename='images/pause.png') }}" alt="pause" />
        </a>

        <a href="{{ url_for('home.congrats') }}" class="end-button">  <!-- đi tới 1 là congrats 2 là it seems like... -->
          <img src="{{ url_for('static', filename='images/end.png') }}" alt="end" />
        </div>
        </a>

        <div class="distance-container">
          <p class="distance-label">Distance:</p>
          <p class="distance-value">8.5 KM</p>
        </div>

    </div>

  </body>
</html>

app/templates/home/set_goal.html
{% extends "home/layout.html" %} {% block title %} Home {% endblock %} {% block head %} {{ super() }}
<!-- Link to the CSS set_goal page -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/set_goal.css') }}" />
<link href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@400;700&display=swap" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css2?family=Joan&display=swap" rel="stylesheet" />

{% endblock %} {% block content %}

<!-- Main content of the about us page -->
<div class="main">
    <div class="overlap-wrapper">
        <div class="setgoal-container">
            <p>Set goal</p>
            <a href="{{ url_for('home.homepage') }}" class="exit-button">
                <img src="{{ url_for('static', filename='images/close_icon.png') }}" alt="Close" class="exit-icon" />
            </a>
        </div>

        <!-- Form to set goal -->
        <form method="post" action="{{ url_for('home.set_goal') }}">
            <div class="goal-container">
                <!-- Must have name="goal" -->
                <input type="number" id="goal" name="goal" class="goal-input" value="0" min="0" max="999" step="any" />
                <span class="goal-unit">KM</span>
            </div>

            <button class="savebtn" type="submit">Save</button>
        </form>
    </div>
    {% endblock %}
</div>